### ISSUE TITLE
h3ronpy : python 3.7 build issue

### ISSUE THREAD

**Issue by jayepraveen999** [nmandery/h3ronpy#17]
Hi. Firstly this is a great library to work with h3indexes. 
However, I have a weird error that I faced when trying to `pip install h3ronpy` in `python3.7`.
The following are the last lines of the error!

`  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Checking for Rust toolchain....
      Traceback (most recent call last):
        File "/home/airflow/.local/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/airflow/.local/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/airflow/.local/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-4_vsukfz/overlay/lib/python3.7/site-packages/maturin/__init__.py", line 140, in prepare_metadata_for_build_wheel
          output = subprocess.check_output(["cargo", "--version"]).decode(
        File "/usr/local/lib/python3.7/subprocess.py", line 411, in check_output
          **kwargs).stdout
        File "/usr/local/lib/python3.7/subprocess.py", line 488, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
          restore_signals, start_new_session)
        File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      PermissionError: [Errno 13] Permission denied: 'cargo'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

I found this weird because the other I could install the package in python3.9 without anyissues. 

Even though the error says `permission denied: 'cargo'`, I think there is a python dependency issue.

Thanks!

**Comment by nmandery** [comment]
Great to hear the library is useful to you!

I removed python 3.7 support in version 0.16 as I noticed current `geopandas` also requires python 3.8 or newer. Seems that was a little early as python 3.7 is not end-of-life yet.

There are two possible solutions for you: You can either use h3ronpy 0.15 which should compile just fine (or even is available as wheel), or build the current version from source after undoing [this change](https://github.com/nmandery/h3ronpy/commit/c3707bd0f663fd0988f38de8b4ec6d1d7f88ab75) - it should compile just fine. You can build the wheel with `maturin build --release` -  see the readme in this repo.

**Comment by nmandery** [comment]
I just released [v0.16.1](https://github.com/nmandery/h3ronpy/releases/tag/v0.16.1) which includes python 3.7 support again. Precompiled wheels are on PyPI.
